version: '3'

networks:
  backend:

services:
  postgres:
    image: postgres
    ports:
      - ${APP_POSTGRES_PORT:-5432}:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 3x4mpl3

  app:
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    command: sh -c './bin/dev'
    env_file: .env
    volumes:
      - .:/app/
      - bundler_gems:/usr/local/bundle/
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - postgres

volumes:
  bundler_gems:
  node_modules: